### ISSUE TITLE
Upcoming (breaking?) changes to NTNU schedule API.

### ISSUE THREAD

**Issue by runemart** [adamcik/plan#49]
Got this message from NTNU IT: 

God dag.

Iløpet av november - desember blir Syllabus oppgradert til ny versjon.  I den forbindelse
vil tenestelaget slutte å levere timeplandata og TIA vil overta leveransane.

Har du fortsatt kontakt med Thomas Adamcik slik at han kan bli varsla?

Tusen takk og ha ei fin helg.

Mvh.

Trond.
--
Trond Kandal

**Comment by adamcik** [comment]
This should be resolved as the site now uses the "hidden" API that ntnu.no uses.
