### ISSUE TITLE
Unable to add IMT*-subjects 

### ISSUE THREAD

**Issue by harahauk** [adamcik/plan#52]
I am unable to add subjects that start with IMT*
For example: IMT4115, IMT4113, IMT4110
They are scheduled:
http://www.ntnu.no/studier/emner/IMT4110#tab=timeplan

Error description:
Couldn't add one or more courses
 Adding the following courses failed:
IMT4110
Back to your schedule.

**Comment by adamcik** [comment]
Non Trondheim courses did not get loaded as one of the database fields is a fixed size varchar and chokes on one of the room names if memory serves.

I'm also undecided about:

1. If I should add a campus field to courses.
2. If the UI forms should indicate campus or filter by it when showing courses in the autocomplete.

I think if the extra model + field gets added, the scrapper gets updated and the varchar fixed I could import everything and figure out part two later.

**Comment by adamcik** [comment]
Not that this fixes the issue, but I've updated `TIMETABLE_INSTITUTION = 'Trondheim NTNU'` in the live settings, hopefully making the current limitation more clear if nothing else.

**Comment by adamcik** [comment]
This has now been fixed with c38fbbc0e255ad5f7c867087477bac1260197811 back in April.
