### ISSUE TITLE
Add option to see timetables for future semesters

### ISSUE THREAD

**Issue by GittinGud** [adamcik/plan#53]
For example: going to https://ntnu.1024.no/2018/fall/ right now shows a 404-type page. I understand some courses may not have published their timetables yet, but many have! Support for just the next semester would be enough.

**Comment by adamcik** [comment]
Imports are not automatic, they rely on me manually running a few commands every semester (and potentially a few times a semester to do updates).

Once new semester is loaded, but not yet active, say in December there is supposed to be a banner announcing the new semester on all previous noes. Not sure if this works these days, but I honestly don't think it adds much value any more.

Anyway, I've just loaded the fall semester so, not much more to do from my side. I'll try and re-import mid or late august to try and catch any changes then.
