### ISSUE TITLE
ipv6 only

### ISSUE THREAD

**Issue by joleeee** [adamcik/plan#55]
Virker som siden ikke lenger har en ipv4 addresse, som gjør at jeg må bruke VPN for å se kalenderen min :(

```sh
~ $ ping ntnu.1024.no
ping: cannot resolve ntnu.1024.no: Unknown host
~ $ ping6 ntnu.1024.no
PING6(56=40+8+8 bytes) fd7a:115c:a1e0:ab12:4843:cd96:626a:413a --> 2001:67c:29f4::60
16 bytes from 2001:67c:29f4::60, icmp_seq=0 hlim=53 time=36.482 ms
16 bytes from 2001:67c:29f4::60, icmp_seq=1 hlim=53 time=26.854 ms
16 bytes from 2001:67c:29f4::60, icmp_seq=2 hlim=53 time=24.772 ms
```

```sh
~ $ dig +short CNAME ntnu.1024.no
delta.1024.no.
~ $ dig +short A delta.1024.no   
~ $ dig +short AAAA delta.1024.no
2001:67c:29f4::60
```

**Comment by Zyron** [comment]
Hei Jonas,

Du får bruke www.CalOne.com inntil videre da ..

**Comment by joleeee** [comment]
Tja er det et konkurrerende produkt? Klarer meg med VPN også inntil videre :))

**Comment by Zyron** [comment]
Har mye av den samme funksjonaliteten ja. Hovedforskjellen er at det mulig å legge inn egne events, som f.eks gruppemøter, kollokviegrupper, etc.

**Comment by adamcik** [comment]
Whoops, bommet tydeligvis når jeg automatiserte noe DNS greier igår. Fikset nå, og har slått av skriptet som hadde feilen.

Takk for feilsøking!

**Comment by adamcik** [comment]
> Har mye av den samme funksjonaliteten ja. Hovedforskjellen er at det mulig å legge inn egne events, som f.eks gruppemøter, kollokviegrupper, etc.

Way back when mens jeg ennå studerte hadde jeg støtte for innleveringer. Dvs egne "events" med en frist/tid. Men var i praksis ingen andre enn meg som brukte det. Så fjernet støtten.

Men bra om det funker for ditt system, er kanskje en annen dynamikk når du kobler det opp mot stud mail.
